name: Push Container
on:
  push:
    branches:
      - master
jobs:
  build:
    uses: rosvik/workflows/.github/workflows/push-container.yml@main
    with:
      containerfile: Containerfile
      image: rosvik/string.248.no
      tag: ${{ github.ref_name }} # git tag or short branch name
      registry_url: cubby.no
      registry_username: ${{ vars.REGISTRY_USER }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
